apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: __CLUSTER__.__DOMAIN__
  name: bastions
spec:
  image: __IMAGE__
  machineType: __MTYPE__
  maxSize: 1
  maxSize: 1
  role: Bastion
  subnets:
  - utility-__REGION__a
  - utility-__REGION__b
  - utility-__REGION__c
