apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: __CLUSTER__.__DOMAIN__
  name: master-__REGION__a
spec:
  image: __IMAGE__
  machineType: __MTYPE__
  maxSize: 1
  maxSize: 1
  role: Master
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - __REGION__a
