apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: __CLUSTER__.__DOMAIN__
  name: nodes
spec:
  image: __IMAGE__
  machineType: __MTYPE__
  maxSize: __NODECOUNT__
  maxSize: __NODECOUNT__
  role: Node
  rootVolumeSize: 100
  rootVolumeType: gp2
  subnets:
  - __REGION__a
  - __REGION__b
  - __REGION__c
